[project]
name = "soulx-podcast"
description = "ComfyUI-SoulX-Podcast is a custom node plugin for ComfyUI that packages the core functionality of SoulX-Podcast (long-form, multi-speaker, multi-dialect podcast voice generation) into a visual node workflow."
version = "1.0.0"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]

dependencies = ["s3tokenizer", "diffusers", "torch", "transformers==4.57.1", "onnxruntime", "einops", "librosa", "scipy"]

[project.urls]
Repository = "https://github.com/flybirdxx/ComfyUI-SoulX-Podcast"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/flybirdxx/ComfyUI-SoulX-Podcast/wiki"
"Bug Tracker" = "https://github.com/flybirdxx/ComfyUI-SoulX-Podcast/issues"

[tool.comfy]
PublisherId = "flybirdxx"
DisplayName = "ComfyUI-SoulX-Podcast"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility
